version: "3.6"
services:
  main:
    build: .
    ports:
      - "${PORT-3000}:3000"
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT:?}
      S3_BUCKET: ${S3_BUCKET:?}
      S3_KEY: ${S3_KEY:?}
      S3_REGION: ${S3_REGION:?}
      S3_SECRET: ${S3_SECRET:?}
  minio:
    image: minio/minio
    volumes:
      - ${VOLUME_MINIO_PATH}:/${S3_BUCKET}
    ports:
      - ${PORT_MINIO}:9000
      - ${PORT_MINIO_CONSOLE}:9001
    environment:
      MINIO_ACCESS_KEY: ${S3_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET}
    command: ["server", "--console-address", ":9001", "${S3_BUCKET}"]
