name: Build and push image
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for test
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: main
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Start buildx container
        run: |
          docker buildx create --use
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sevenc7c
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push --tag sevenc7c/sonolus-sus-server:latest .
